### ISSUE TITLE
How to use CPU to run the test.py?

### ISSUE THREAD

**Issue by be-nice-do-better** [yiranran/APDrawingGAN#23]
Can I run test.py using CPU instead of GPU please?

Currently when run:
```
python test.py --dataroot dataset/data/test_single --name formal_author --model test --dataset_mode single --norm batch 
--use_local --which_epoch 300
```
got error:

> Traceback (most recent call last):
>   File "test.py", line 10, in <module>
>     opt = TestOptions().parse()
>   File "C:\repos\zzz\APDrawingGAN\options\base_options.py", line 131, in parse
>     torch.cuda.set_device(opt.gpu_ids[0])
>   File "C:\repos\zzz\APDrawingGAN\venv\lib\site-packages\torch\cuda\__init__.py", line 314, in set_device
>     torch._C._cuda_setDevice(device)
> AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

**Comment by be-nice-do-better** [comment]
found it, need to put `--gpu_ids -1` in the command, thanks
